### ISSUE TITLE
请问本项目是否是测试项目？

### ISSUE THREAD

**Issue by kkatblm** [kpboluome/crypto#1]
如果是测试项目，请忽略下文。

给出几点建议：
1. 和hash项目有重复：）
2. 从技术角度。md5和sha1属于哈希摘要，并不属于crypto（加密）。之所以会被nodejs归入crypto库是因为加密时通常会使用到哈希摘要。

@Super-Pig

**Comment by Super-Pig** [comment]
嗯，该项目目前只包含两个方法：md5，sh1，是和hash项目重复的
稍后更新，把该项目的这两个方法删掉，如果需要调用 md5 就引用 hash 的 npm 包
建议保留crypto项目，以后可能会用到 rsa 或者其他的加密方法，都放到这个项目中

**Comment by kkatblm** [comment]
已经有人在依赖这个包了吗？
